#spring.application.name=dog-service

#spring.application.name=dog-service

spring:
  application:
    name: dog-service # Name of the microservice
  datasource:
    url: jdbc:h2:mem:dogdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true        # Enable H2 Console for web access
      path: /h2-console    # Access at http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update     # Automatically update schema for development
    show-sql: true          # Log SQL queries
    properties:
      hibernate:
        format_sql: true    # Pretty-print the SQL in logs

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.wfarooq.dog_service: DEBUG # Replace with your actual base package
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

