package com.wfarooq.dog_service.dog.constants;

public enum DogBreed {
    ROTTWEILER,
    GERMAN_SHEPHERD,
    AMERICAN_BULLY,
    BELGIAN_MALINOIS,
    DOBERMAN,
    BOXER,
    CANE_CORSO,
    GIANT_SCHNAUZER,
    BULLMASTIFF,
    PRESA_CANARIO,
    BOERBOEL,
    ALAPAHA_BLUE_BLOOD_BULLDOG,
    DOGO_ARGENTINO,
    TURKISH_KANGAL,
    CENTRAL_ASIAN_SHEPHERD,
    TOSA_INU,
    AKITA,
    NEAPOLITAN_MASTIFF
}

